apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: ftps
  template:
    metadata: 
      labels: 
        app: ftps
    spec:
      restartPolicy: Always
      containers:
        - name: ftps
          image: monftps:latest
          imagePullPolicy: Never
          ports:
            - containerPort : 21
            - containerPort : 30020
