apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: monmysql:latest
          livenessProbe:
            exec:
              command:
              - pgrep
              - mysql
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
            - containerPort: 3306
          imagePullPolicy: Never
          volumeMounts:
            - name: mysql-persistent
              mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-persistent
        persistentVolumeClaim:
          claimName: mysql-pv-claim