apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf-deploy
spec:
    selector:
        matchLabels:
            app: telegraf
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: telegraf
        spec:
            restartPolicy: Always
            containers:
                - image: montelegraf:latest
                  imagePullPolicy: Never
                  name: telegraf
                  envFrom:
                      - secretRef:
                          name: telegraf-secrets
                  volumeMounts:
                      - name: telegraf-config-volume
                        mountPath: /etc/telegraf.conf
                        subPath: telegraf.conf
                        readOnly: true
                      - name: docker-socket
                        mountPath: "/var/run/docker.sock"
            volumes:
                - name: telegraf-config-volume
                  configMap:
                    name: telegraf-config
                - name: docker-socket
                  hostPath:
                    path: /var/run/docker.sock
