apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
        - name: wordpress
          image: monwordpress:latest
          livenessProbe:
            exec:
              command:
              - sh
              - liveness.sh
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
            - containerPort: 9000
            - containerPort: 5050
          imagePullPolicy: Never