apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secrets
type: Opaque
stringData:
    INFLUXDB_DB: telegraf
    INFLUXDB_URL: http://influxdb-svc:8086
    INFLUXDB_USER: telegraf
    INFLUXDB_USER_PASSWORD: telegraf
