apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.200
  selector:
    app: ftps
  ports:
    - name : active1-ftp
      protocol: TCP
      port: 21
    - name : passive1-ftp
      protocol: TCP
      port: 30020
