apiVersion: v1
kind: Service
metadata:
        name: grafana-svc
        annotations:
            metallb.universe.tf/allow-shared-ip: sharing key
spec:
        type: LoadBalancer
        loadBalancerIP: 172.17.0.200
        selector:
                app: grafana
        ports:
                - name: http
                  protocol: TCP
                  port: 3000
                  targetPort: 3000
