apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  loadBalancerIP: 172.17.0.200
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
