apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  loadBalancerIP: 172.17.0.200
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306