apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: php-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
