apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: php-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 172.17.0.200
