apiVersion: v1
kind: Service
metadata:
    name: telegraf-svc
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    loadBalancerIP: 172.17.0.200
    selector:
        app: telegraf
    ports:
        - port: 35000
