apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 172.17.0.200
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http
      protocol: TCP
      port: 5050
      targetPort: 5050